/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000002_000000000002.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000002_000000000012.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000004_000000000004.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000004_000000000024.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000006_000000000007.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000006_000000000036.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000008_000000000009.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000008_000000000048.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000010_000000000012.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000010_000000000060.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000012_000000000014.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000012_000000000072.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000014_000000000016.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000014_000000000084.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000016_000000000019.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000016_000000000096.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000018_000000000021.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000018_000000000108.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000020_000000000024.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000020_000000000120.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000022_000000000026.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000022_000000000132.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000024_000000000028.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000024_000000000144.dimacs
Traceback (most recent call last):
  File "get_complement_graph.py", line 29, in <module>
    complement_graph(sys.argv[1], "complement/" + sys.argv[1].split('.')[0] +  "_complement." + sys.argv[1].split('.')[1])
IndexError: list index out of range
./vcFromClique.sh: line 14: complement/_complement.dimacs: No such file or directory
1

/Users/koselev/Desktop/AlgEng/algorithm-engineering/task-5/scripts/1-random/000026_000000000031.dimacs
